<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <ValidationNamespaceRoot>ReactiveUI.Validation</ValidationNamespaceRoot>
  </PropertyGroup>

  <Import Project="ReactiveUI.Validation.Usings.props" />

  <ItemGroup>
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="DynamicData" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Binding.Expressions" />
    <Using Include="ReactiveUI.Primitives.Concurrency" />
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Disposables" />
    <Using Include="ReactiveUI.Primitives.Signals" />
    <Using Include="ReactiveUI.Primitives.Disposables.Scope" Alias="Disposable" />
    <Using Include="ReactiveUI.Primitives.Concurrency.ISequencer" Alias="IScheduler" />
    <Using Include="ReactiveUI.Primitives.Signals.Signal" Alias="Observable" />
    <Using Include="ReactiveUI.Primitives.RxVoid" Alias="Unit" />
    <Using Include="ReactiveUI.Primitives.Disposables.MultipleDisposable" Alias="CompositeDisposable" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReactiveUI.Validation.Tests" />
    <InternalsVisibleTo Include="ReactiveUI.Validation.AndroidX" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="Microsoft.Bcl.HashCode" />
  </ItemGroup>
</Project>
